receivers:
  nginx:
    endpoint: "http://web:80/status"
    collection_interval: 10s
  filelog:
    include: ["/var/log/nginx/access.log"]
    operators:
      - type: regex_parser
        regex: (?P<remote_addr>((?:[0-9]{1,3}\.){3}[0-9]{1,3})) (?P<dash>\S+) (?P<remote_user>\S+) \[(?P<time_local>[\w:\/]+\s[+|-]\d{4})\] \"(?P<request>\S+)\s?(?P<path>\S+)?\s?(?P<protocol>\S+)?\" (?P<status_code>\d{3}|-) (?P<body_bytes_sent>\d+|-)\s?\"?(?P<http_referer>[^\"]*)\"?\s\"?(?P<http_user_agent>[^\"]*)\"\s\"?(?P<http_x_forwarded_for>[^\"]*)
        timestamp:
          parse_from: attributes.time_local
          layout: '%d/%b/%Y:%H:%M:%S.%f %z'

exporters:
  logging:
    loglevel: debug

processors:
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["http.request.body.size"], attributes["body_bytes_sent"])
          - delete_key(attributes, "body_bytes_sent")
          - set(attributes["http.request.method"], attributes["request"])
          - delete_key(attributes, "request")

service:
  pipelines:
    metrics:
      receivers: [nginx]
      exporters: [logging]
    logs:
      receivers: [filelog]
      processors: [transform]
      exporters: [logging]
