version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./html:/usr/share/nginx/html
  collector:
    image: otel/opentelemetry-collector-contrib:0.81.0
    command: ["--config=/etc/otel/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otel/collector-config.yaml
      - ./log:/var/log/nginx